name: Test the main branch
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          check-latest: true
      - run: go install github.com/rogpeppe/go-internal/cmd/testscript@latest
      - run: go install cuelang.org/go/cmd/cue@v0.4.3
      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - run: ./tests/all-tests.sh
